### ISSUE TITLE
Uncaught TYPO3 Exception: #1595862844: Content returned from Matomo Reporting API is not JSON encoded: 

### ISSUE THREAD

**Issue by FBuchholz** [mittwald/typo3-mw-matomo-widget#3]
Wir bekommen folgende Fehlermeldung. Aktuell glauben wird, dass die Abfrage nicht die Proxy Exzeption beachtet oder das SSL Cert des Firewall nicht nutzt. Gibt es eine Möglichkeit, hierzu mehr Information sich anzeigen zu lassen, z.B. in einem Log?

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1595862844: Content returned from Matomo Reporting API is not JSON encoded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> | Brotkrueml\MatomoWidgets\Exception\InvalidResponseException thrown in file /var/www/website/vendor/brotkrueml/typo3-matomo-widgets/Classes/Connection/MatomoConnector.php in line 64. Requested URL: https://wajax/dashboard/widget/content?token=--AnonymizedToken--&widget=matomo_widgets.p.visitsSummary.actionsPerMonth

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1595862844: Content returned from Matomo Reporting API is not JSON encoded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> | Brotkrueml\MatomoWidgets\Exception\InvalidResponseException thrown in file /var/www/website/vendor/brotkrueml/typo3-matomo-widgets/Classes/Connection/MatomoConnector.php in line 64. Requested URL: https://www./typo3/ajax/dashboard/widget/content?token=--AnonymizedToken--&widget=matomo_widgets.-.visitsSummary.visitsPerDay

**Comment by derhansen** [comment]
Ich glaub du bist hier falsch, denn diese TYPO3 Erweiterung hier ist `Mittwald\MatomoWidget` und nicht `Brotkrueml\MatomoWidgets`. Hier geht es zum Issue Tracker der Extension: https://github.com/brotkrueml/typo3-matomo-widgets
